### ISSUE TITLE
create_user endpoint requires both mentee and mentor fields

### ISSUE THREAD

**Issue by tpeek** [PuPy-Python/mentorship-app#105]
After hooking up the frontend to the /user 'POST' endpoint, I'm noticing that both mentee and mentor profiles are required. If the json doesn't include a mentee key or mentor key, the server sends back a 500. If you send both those keys with values as empty dictionaries, the server sends back a 400, and mentions that the 'goals' field is required for mentees and 'mentee_capacity' is required for mentors.

We should update this endpoint to check for mentee/mentor keys and make the appropriate objects based on that.

**Comment by johnnyodonnell** [comment]
Good catch! This should be fixed once we merge in this PR: https://github.com/PuPy-Python/mentorship-app/pull/107
