### ISSUE TITLE
Delete Old Django View Routes

### ISSUE THREAD

**Issue by CarolynKollstedt** [PuPy-Python/mentorship-app#108]

**Comment by CarolynKollstedt** [comment]
1) Delete https://github.com/PuPy-Python/mentorship-app/blob/master/mentorship/urls.py#L30-L57
2) Delete "hello" in base route that loads REACT application: https://github.com/PuPy-Python/mentorship-app/blob/c7ed1e0ea9bd0ddd7cbbfa209d841e903231ec8b/mentorship/urls.py#L27

**Comment by justinhernandez** [comment]
[PR](https://github.com/PuPy-Python/mentorship-app/pull/109) was merged so closing issue
