### ISSUE TITLE
User: Login

### ISSUE THREAD

**Issue by CCallahanIV** [PuPy-Python/mentorship-app#29]
_As a User with an existing account, I would like to be able to login and out._

The purpose of this ticket is to create login/logout capabilities between React and Django Rest Framework.

**Acceptance Criteria**
1. url for login page is `/login`
2. url for logging out is `/logout`
3. User can login with their email or username and password
4. After logging in, User is authenticated for using the rest of the application.
5. After logging out, User is no longer authenticated for any private part of the application (but can still see public pages).

**Comment by justinhernandez** [comment]
@CarolynKollstedt closing this issue since it was moved to the "Done" column on the project board.
