### ISSUE TITLE
Profile Model: Update

### ISSUE THREAD

**Issue by justinhernandez** [PuPy-Python/mentorship-app#40]
Edit the [Profile model class](https://github.com/PuPy-Python/mentorship-app/blob/master/mentorship_profile/models.py#L17-L81) and add the following new fields:

- [ ] Biography (500 char max) (optional)
- [ ] PuPPy slack handle (optional)
- [ ] LinkedIn URL (optional)

**Comment by dsnowb** [comment]
Note - all of these fields were already present in the file, just added a character constraint to biography.

**Comment by justinhernandez** [comment]
@dsnowb 

Digging into the database, these items are NOT being saved to the `mentorship_profile_profile` table.

<img width="861" alt="screen shot 2018-08-21 at 6 47 33 pm" src="https://user-images.githubusercontent.com/23852/44438155-b10bde80-a572-11e8-8a2b-76543b09d71f.png">

**Comment by justinhernandez** [comment]
@CarolynKollstedt closing this issue since it was moved to the "Done" column on the project board.
