### ISSUE TITLE
Profile Model Update: Years of Experience

### ISSUE THREAD

**Issue by CCallahanIV** [PuPy-Python/mentorship-app#51]
Add to the profile model a single select field named 'years_industry_experience' with choices:

* 0
* 1 - 2
* 3 - 7
* 7 +

Class: [Model Profile](https://github.com/PuPy-Python/mentorship-app/blob/master/mentorship_profile/models.py#L17)

**Comment by jem1031** [comment]
The last two choices are overlapping. Should I change it to 3-6 and 7+?

**Comment by CCallahanIV** [comment]
@jem1031 , that's a really good point - please change the ranges as you described!

**Comment by tpeek** [comment]
I find these ranges kinda confusing. If I have 6 months of experience, I have to choose 0? If I have 2 and a half years of experience, I have to choose 1-2? Maybe we should change the options so that they all overlap, to make it clear what the ranges are:

- 0 - 1 
- 1 - 3
- 3 - 7
- 7 +

**Comment by jem1031** [comment]
This makes sense to me. See PR https://github.com/PuPy-Python/mentorship-app/pull/85
